# Generated by Django 3.1.4 on 2020-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0002_securities_securitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrytype',
            name='short',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industrytype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
