# Generated by Django 3.1.4 on 2020-12-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0004_auto_20201228_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='industries',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
