# Generated by Django 3.1.4 on 2020-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0006_auto_20201229_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='dsiplay_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
