# Generated by Django 3.1.4 on 2020-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0007_auto_20201229_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='securities',
            name='code',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securities',
            name='dsiplay_name',
            field=models.CharField(max_length=50),
        ),
    ]
