# Generated by Django 3.1.4 on 2020-12-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0008_auto_20201229_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='dsiplay_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='securityType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securitytype'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
