# Generated by Django 3.1.4 on 2020-12-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0009_auto_20201229_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_date', models.DateField()),
                ('total_operating_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('operating_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_operating_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('operating_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('operating_tax_surcharges', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sale_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('administration_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('exploration_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('financial_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('asset_impairment_loss', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fair_value_variable_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('investment_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('invest_income_associates', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('exchange_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_items_influenced_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('operating_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('subsidy_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('non_operating_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('non_operating_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('disposal_loss_non_current_liability', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_items_influenced_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('income_tax', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_items_influenced_net_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('np_parent_company_owners', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('minority_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('eps', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('basic_eps', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('diluted_eps', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_composite_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_composite_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('ci_parent_company_owners', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('ci_minority_owners', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('interest_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('premiums_earned', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('commission_income', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('interest_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('commission_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('refunded_premiums', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_pay_insurance_claims', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('withdraw_insurance_contract_reserve', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('policy_dividend_payout', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reinsurance_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('non_current_asset_disposed', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_earnings', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reportSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.reportsource')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
    ]
