# Generated by Django 3.1.4 on 2021-01-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0010_incomestatement_reportsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0, null=True)),
                ('full_name', models.CharField(default=None, max_length=100, null=True)),
                ('short_name', models.CharField(default=None, max_length=40, null=True)),
                ('a_code', models.CharField(default=None, max_length=12, null=True)),
                ('b_code', models.CharField(default=None, max_length=12, null=True)),
                ('h_code', models.CharField(default=None, max_length=12, null=True)),
                ('fullname_en', models.CharField(default=None, max_length=100, null=True)),
                ('shortname_en', models.CharField(default=None, max_length=40, null=True)),
                ('legal_representative', models.CharField(default=None, max_length=40, null=True)),
                ('register_location', models.CharField(default=None, max_length=100, null=True)),
                ('office_address', models.CharField(default=None, max_length=150, null=True)),
                ('zipcode', models.CharField(default=None, max_length=10, null=True)),
                ('register_capital', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('currency_id', models.IntegerField(default=None, null=True)),
                ('currency', models.CharField(default=None, max_length=32, null=True)),
                ('establish_date', models.DateField(default=None, null=True)),
                ('website', models.CharField(default=None, max_length=80, null=True)),
                ('email', models.CharField(default=None, max_length=80, null=True)),
                ('contact_number', models.CharField(default=None, max_length=60, null=True)),
                ('fax_number', models.CharField(default=None, max_length=60, null=True)),
                ('main_business', models.CharField(default=None, max_length=500, null=True)),
                ('business_scope', models.CharField(default=None, max_length=4000, null=True)),
                ('description', models.CharField(default=None, max_length=4000, null=True)),
                ('tax_number', models.CharField(default=None, max_length=50, null=True)),
                ('license_number', models.CharField(default=None, max_length=40, null=True)),
                ('pub_newspaper', models.CharField(default=None, max_length=120, null=True)),
                ('pub_website', models.CharField(default=None, max_length=120, null=True)),
                ('secretary', models.CharField(default=None, max_length=40, null=True)),
                ('secretary_number', models.CharField(default=None, max_length=60, null=True)),
                ('secretary_fax', models.CharField(default=None, max_length=60, null=True)),
                ('secretary_email', models.CharField(default=None, max_length=80, null=True)),
                ('security_representative', models.CharField(default=None, max_length=40, null=True)),
                ('province_id', models.CharField(default=None, max_length=12, null=True)),
                ('province', models.CharField(default=None, max_length=60, null=True)),
                ('city_id', models.CharField(default=None, max_length=12, null=True)),
                ('city', models.CharField(default=None, max_length=60, null=True)),
                ('industry_id', models.CharField(default=None, max_length=12, null=True)),
                ('industry_1', models.CharField(default=None, max_length=60, null=True)),
                ('industry_2', models.CharField(default=None, max_length=60, null=True)),
                ('cpafirm', models.CharField(default=None, max_length=200, null=True)),
                ('lawfirm', models.CharField(default=None, max_length=200, null=True)),
                ('ceo', models.CharField(default=None, max_length=100, null=True)),
                ('comments', models.CharField(default=None, max_length=100, null=True)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
    ]
