# Generated by Django 3.1.4 on 2021-01-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0011_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0, null=True)),
                ('company_name', models.CharField(default=None, max_length=100, null=True)),
                ('code', models.CharField(default=None, max_length=12, null=True)),
                ('change_date', models.DateField(default=None, null=True)),
                ('pub_date', models.DateField(default=None, null=True)),
                ('change_reason_id', models.IntegerField(default=0, null=True)),
                ('change_reason', models.CharField(default=None, max_length=120, null=True)),
                ('share_total', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_non_trade', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_start', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_nation', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_nation_legal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_instate_legal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_outstate_legal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_natural', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_raised', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_inside', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_convert', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_perferred', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_other_nontrade', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_legal_issue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_strategic_investor', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_fund', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_normal_legal', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_other_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_nation_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_nation_legal_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_instate_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('legal_of_other_instate_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('natural_of_other_instate_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('outstate_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('legal_of_outstate_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('natural_of_outstate_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_trade_total', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_rmb', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_b', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_b_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_h', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_h_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_management', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_management_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('share_other_trade', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('control_shareholder_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('core_employee_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('individual_fund_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_legal_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('other_limited', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
    ]
