# Generated by Django 3.1.4 on 2021-01-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0014_auto_20210106_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharelodersShareChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0, null=True)),
                ('company_name', models.CharField(default=None, max_length=100, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('pub_date', models.DateField(default=None, null=True)),
                ('type', models.IntegerField(default=0, null=True)),
                ('shareholder_id', models.IntegerField(default=0, null=True)),
                ('shareholder_name', models.CharField(default=None, max_length=200, null=True)),
                ('change_number', models.IntegerField(default=0, null=True)),
                ('change_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('price_ceiling', models.CharField(default=None, max_length=200, null=True)),
                ('after_change_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderTop10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0, null=True)),
                ('company_name', models.CharField(default=None, max_length=100, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('pub_date', models.DateField(default=None, null=True)),
                ('change_reason_id', models.IntegerField(default=0, null=True)),
                ('change_reason', models.CharField(default=None, max_length=120, null=True)),
                ('shareholder_rank', models.IntegerField(default=0, null=True)),
                ('shareholder_name', models.CharField(default=None, max_length=200, null=True)),
                ('shareholder_name_en', models.CharField(default=None, max_length=200, null=True)),
                ('shareholder_id', models.IntegerField(default=0, null=True)),
                ('shareholder_class_id', models.IntegerField(default=0, null=True)),
                ('shareholder_class', models.CharField(default=None, max_length=120, null=True)),
                ('share_number', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('share_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('sharesnature_id', models.IntegerField(default=0, null=True)),
                ('sharesnature', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('share_pledge_freeze', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('share_pledge', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('share_freeze', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderFloatingTop10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0, null=True)),
                ('company_name', models.CharField(default=None, max_length=100, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('pub_date', models.DateField(default=None, null=True)),
                ('change_reason_id', models.IntegerField(default=0, null=True)),
                ('change_reason', models.CharField(default=None, max_length=120, null=True)),
                ('shareholder_rank', models.IntegerField(default=0, null=True)),
                ('shareholder_name', models.CharField(default=None, max_length=200, null=True)),
                ('shareholder_name_en', models.CharField(default=None, max_length=200, null=True)),
                ('shareholder_class_id', models.IntegerField(default=0, null=True)),
                ('shareholder_class', models.CharField(default=None, max_length=120, null=True)),
                ('share_number', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('share_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('sharesnature_id', models.IntegerField(default=0, null=True)),
                ('sharesnature', models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
        migrations.CreateModel(
            name='HolderNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(default=None, null=True)),
                ('pub_date', models.DateField(default=None, null=True)),
                ('share_holders', models.IntegerField(default=0, null=True)),
                ('a_share_holders', models.IntegerField(default=0, null=True)),
                ('b_share_holders', models.IntegerField(default=0, null=True)),
                ('h_share_holders', models.IntegerField(default=0, null=True)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.securities')),
            ],
        ),
    ]
