# Generated by Django 3.1.4 on 2021-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0015_holdernum_shareholderfloatingtop10_shareholdertop10_shareloderssharechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securities',
            old_name='dsiplay_name',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='securitytype',
            name='des',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
