# Generated by Django 3.1.4 on 2021-01-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0016_auto_20210109_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='securities',
            name='securityType2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondType', to='stock_hs_A.securitytype'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='securityType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainType', to='stock_hs_A.securitytype'),
        ),
    ]
