# Generated by Django 3.1.5 on 2021-01-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0017_auto_20210109_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('tsCode', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('isOpen', models.BooleanField(default=True)),
                ('isUpdate', models.BooleanField(default=False)),
                ('exchagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_hs_A.exchange')),
            ],
        ),
    ]
