# Generated by Django 3.1.5 on 2021-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_hs_A', '0018_exchange_tradeday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
